import React, { useState } from "react";
import { FileText, ShieldCheck, Download } from "lucide-react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts";
import { C } from "../../theme/tokens.js";
import { T } from "../../data/translations.js";
import { rainWindow } from "../../data/mockData.js";
import SectionEyebrow from "../primitives/SectionEyebrow.jsx";

export default function ClaimView({ lang }) {
  const t = T[lang];
  const [generated, setGenerated] = useState(false);

  return (
    <div className="ks-rise">
      <SectionEyebrow>{t.claimEyebrow}</SectionEyebrow>
      <h1 className="ks-display text-[26px] font-semibold mb-1">{t.claimTitle}</h1>
      <p className="text-[13px] opacity-70 mb-4 max-w-xl">
        Combines geo-tagged photos, satellite NDVI history and local weather into a structured assessment. This is
        assistance evidence — the farmer or officer still files the official claim.
      </p>

      {!generated ? (
        <div className="ks-card rounded-lg p-5 max-w-2xl">
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <div className="ks-mono text-[10.5px] uppercase tracking-wide opacity-55 mb-1">Suspected cause</div>
              <div className="text-[14px] font-medium">Waterlogging — 20–22 Aug rain event</div>
            </div>
            <div>
              <div className="ks-mono text-[10.5px] uppercase tracking-wide opacity-55 mb-1">Photo evidence</div>
              <div className="flex gap-1.5">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="w-12 h-12 rounded-sm" style={{ background: C.paperDeep }} />
                ))}
              </div>
            </div>
          </div>
          <div className="mt-4">
            <div className="ks-mono text-[10.5px] uppercase tracking-wide opacity-55 mb-1">Rainfall in damage window</div>
            <div className="h-28">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={rainWindow} margin={{ top: 4, right: 4, left: -24, bottom: 0 }}>
                  <XAxis dataKey="d" tick={{ fontSize: 10 }} stroke={C.line} />
                  <YAxis tick={{ fontSize: 10 }} stroke={C.line} />
                  <Tooltip contentStyle={{ fontSize: 12, borderRadius: 6 }} />
                  <Bar dataKey="mm" fill={C.monsoon} radius={[3, 3, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
          <button
            onClick={() => setGenerated(true)}
            className="mt-4 px-4 py-2.5 rounded-md font-medium text-[13.5px] flex items-center gap-2"
            style={{ background: C.monsoon, color: C.paper }}
          >
            <FileText size={15} /> Generate evidence report
          </button>
        </div>
      ) : (
        <div className="ks-card rounded-lg p-0 max-w-xl overflow-hidden ks-rise">
          <div className="px-5 py-3 flex items-center justify-between" style={{ background: C.monsoon, color: C.paper }}>
            <div className="flex items-center gap-2">
              <ShieldCheck size={16} />
              <span className="ks-mono text-[12px] tracking-wide">CLM-1042 · CROP DAMAGE EVIDENCE REPORT</span>
            </div>
            <Download size={16} />
          </div>
          <div className="p-5 text-[13px] space-y-3">
            <div className="grid grid-cols-2 gap-y-2">
              <div>
                <div className="ks-mono text-[10px] uppercase opacity-55">Farmer / Plot</div>
                <div>Ram Kumar · GGN-114</div>
              </div>
              <div>
                <div className="ks-mono text-[10px] uppercase opacity-55">Damage window</div>
                <div>20–22 Aug 2026</div>
              </div>
              <div>
                <div className="ks-mono text-[10px] uppercase opacity-55">NDVI drop</div>
                <div style={{ color: C.alert }} className="font-semibold">
                  −31%
                </div>
              </div>
              <div>
                <div className="ks-mono text-[10px] uppercase opacity-55">Rainfall recorded</div>
                <div>90mm over 48h (IMD)</div>
              </div>
            </div>
            <div>
              <div className="ks-mono text-[10px] uppercase opacity-55 mb-1">Photo grid</div>
              <div className="flex gap-1.5">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="w-14 h-14 rounded-sm" style={{ background: C.paperDeep }} />
                ))}
              </div>
            </div>
            <div className="pt-3 text-[11.5px] opacity-70 italic" style={{ borderTop: `1px dashed ${C.line}` }}>
              This is an assistance evidence report generated by KrishiSetu, not an official PMFBY settlement decision.
              Final assessment rests with the insurer / assessing officer.
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
